Update prometheus exporter
was locked at 0.4.17 in this commit `1748e152978f68e7b3dddfea42d1d7b2522f5d66`
due to issues, but this version seems to have problems with
sidekiq 7 during server start up. It errors as below

```shell
NameError: undefined method `call' for class `Redis::Client'
(eval):2:in `alias_method'
(eval):2:in `patch'
/usr/local/bundle/gems/prometheus_exporter-0.4.17/lib/prometheus_exporter/instrumentation/method_profiler.rb:29:in `class_eval'
/usr/local/bundle/gems/prometheus_exporter-0.4.17/lib/prometheus_exporter/instrumentation/method_profiler.rb:29:in `patch'
/usr/local/bundle/gems/prometheus_exporter-0.4.17/lib/prometheus_exporter/middleware.rb:15:in `initialize'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:37:in `new'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:37:in `build'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:166:in `block in build'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:162:in `each'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:162:in `inject'
/usr/local/bundle/gems/actionpack-7.0.4.2/lib/action_dispatch/middleware/stack.rb:162:in `build'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/engine.rb:516:in `block in app'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/engine.rb:512:in `synchronize'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/engine.rb:512:in `app'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/application.rb:372:in `initialize!'
/usr/src/app/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/application.rb:348:in `require_environment!'
/usr/local/bundle/gems/railties-7.0.4.2/lib/rails/application.rb:511:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate:with_data => environment
(See full trace by running task with --trace)
```