Bump caniuse-lite "1.0.30001236" " to 1.0.30001441"
Causing error on build

```
16:01:46 > Step 15/25 : RUN bundle exec rake assets:precompile SECRET_KEY_BASE=a-real-secret-key-is-not-needed-here
16:01:46 > ---> Running in fc080bd14fbd
16:01:52 > yarn install v1.22.19
16:01:52 > [1/4] Resolving packages...
16:01:53 > success Already up-to-date.
16:01:53 > Done in 1.09s.
16:01:55 > Compiling...
16:01:58 > Compilation failed:
16:01:58 > Browserslist: caniuse-lite is outdated. Please run:
16:01:58 > npx browserslist@latest --update-db
16:01:58 > Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
16:01:58 > node:internal/crypto/hash:71
16:01:58 > this[kHandle] = new _Hash(algorithm, xofLen);
16:01:58 > ^
16:01:58 >
16:01:58 > Error: error:0308010C:digital envelope routines::unsupported
16:01:58 > at new Hash (node:internal/crypto/hash:71:19)
16:01:58 > at Object.createHash (node:crypto:133:10)
16:01:58 > at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
16:01:58 > at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
16:01:58 > at /usr/src/app/node_modules/webpack/lib/NormalModule.js:452:10
16:01:58 > at /usr/src/app/node_modules/webpack/lib/NormalModule.js:323:13
16:01:58 > at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
16:01:58 > at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
16:01:58 > at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
16:01:58 > at /usr/src/app/node_modules/babel-loader/lib/index.js:59:103 {
16:01:58 > opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
16:01:58 > library: 'digital envelope routines',
16:01:58 > reason: 'unsupported',
16:01:58 > code: 'ERR_OSSL_EVP_UNSUPPORTED'
16:01:58 > }
16:01:59 >
16:01:59 > Node.js v18.12.1
16:01:59 >
The command '/bin/sh -c bundle exec rake assets:precompile SECRET_KEY_BASE=a-real-secret-key-is-not-needed-here' returned a non-zero code: 1

```