Normalise release names in deploy releases
So that we comply with Helm restrictions:

```
Error: UPGRADE FAILED: invalid release name, must match regex
^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not
longer than 53
```