AP-6260: Add puppeter-core to dependencies and install in app image
This adds puppeteer-core node_modules as a runtime dependency to the app docker image,

This allows us to use puppeteer-core for PDF generation (of means and merits reports)
by the Grover gem. However, it adds all node_modules despite the fact that we are
using esbuild to bundle the JS assets. This is because the Grover gem uses puppeteer-core
to launch a headless browser to generate PDFs, and it needs the puppeteernode_modules to be
present in the image to do this. The esbuild puppeteer will not be used by the Grover gem.

To test if Grover will work the following commands from the root of containerized project
must run without error:

```sh
node -e "require('puppeteer')"
node -e "require('puppeteer-core')"
````

If both of these error then Grover PDF generation will not work and the means and merits report PDFs
will not be generated.

Example rails error if puppeteer is not found:
```
app/services/reports/base_report_creator.rb:18:in 'Reports::BaseReportCreator#pdf_report': Cannot find module 'puppeteer'. The module was found in '/usr/src/app/package.json' however, please run 'npm install' from '/usr/src/app' (Grover::DependencyError)
```

Note that we also move the NODE_ENV=production env var to before the yarn install command,
otherwise the devDependencies will installed, including full puppeteer module.